# Path to your oh-my-zsh installation.
export ZSH="/home/leon/.oh-my-zsh"

# half-life inspired prompt
autoload -Uz vcs_info # Load version control information
autoload -U colors && colors  # Load colors
precmd() { vcs_info }
# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%fon %F{039}%b '
# Set up the prompt (with git branch name)
setopt PROMPT_SUBST
PROMPT='%B%F{099}%n %{$reset_color%}in %F{106}%~ ${vcs_info_msg_0_}%F{166}λ %f'

# don't use colors when using greenscreen theme
THEME=$(xrdb -query | awk '/name/ { print $2 }')
[ "$THEME" = "greenscreen" ] && PROMPT='%B%n %{$reset_color%}in %~ ${vcs_info_msg_0_}λ %f'

setopt autocd     # Automatically cd into typed directory.
stty stop undef       # Disable ctrl-s to freeze terminal.
setopt interactive_comments

# History in cache directory:
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.zsh_history
HIST_STAMPS="yyyy-mm-dd"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# Turn off all beeps
unsetopt BEEP
# Turn off autocomplete beeps
unsetopt LIST_BEEP
# Match files beginning with a . without specifying the dot
setopt globdots
# vim on the command line
set -o vi


[ -f ~/.config/shell/profile ] && source ~/.config/shell/profile
[ -f ~/.config/shell/aliasrc ] && source ~/.config/shell/aliasrc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
