#!/bin/sh

# command shortcuts
alias ls="exa --group-directories-first"
alias ll="ls -l"
alias la="ls -la"
alias cat="bat"

# git
alias glog="git log --branches --oneline --graph --decorate"
alias gdiff="bat \$(git status --porcelain | awk '{ print \$2 }')"
alias udiff="bat \$(git status --porcelain | awk '/^\?\?/ { print \$2 }')"

alias lg="lazygit"

alias suspend="loginctl suspend"

alias scrot='scrot "$HOME/Pictures/Screenshots/%Y-%m-%d_%H%M%S.png"'
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd $LASTDIR'
alias tree="tree --dirsfirst -F"
alias dotfilestree="tree -a . -I .git"

alias wikis="cd $HOME/wikis"

#alias vim="nvim"
alias doom="$HOME/.emacs.d/bin/doom"
alias emacs="emacs -fh"
alias emacsc="emacsclient -c -a 'emacs'"
alias emacsd="emacs --daemon"

# config shortcuts
alias zshrc="$EDITOR $HOME/.zshrc"
alias vimrc="$EDITOR $HOME/.config/nvim/init.vim"
alias sxhkdrc="$EDITOR $HOME/.config/sxhkd/sxhkdrc"
alias tmuxcf="$EDITOR $HOME/.config/tmux/.tmux.conf"

# fzf
alias vimfzf="vim \$(fzf)"
alias cdfzf="cd \$(find * -type d | fzf)"

clip() {
    printf "%s" "$1" | xclip -sel clipboard
}

# copy/paste file contents to clipcoard on WSL
copy() {
    clip.exe < "$1"
}
paste() {
    powershell.exe Get-Clipboard | sed 's/\r//'
}
