#!/bin/sh

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/bin/dmenu"
export PATH="$PATH:$HOME/.local/bin/git"
export PATH="$PATH:$HOME/.emacs.d/bin"

# default programs
export EDITOR="nvim"
export TERM="st-256color"
export SHELL="zsh"
export BROWSER="firefox"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

#. "$HOME/.cargo/env"
