#!/bin/sh

xrdb -merge $HOME/.Xresources

xbanish &
setxkbmap -option caps:ctrl_modifier
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

picom --experimental-backends -b
feh --bg-scale Pictures/Wallpapers/archbox.png
dunst &

dwm-status &
exec dbus-run-session dwm
